/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jac482javafxmlapplication;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

/**
 * Main class definition for the application.
 * <br>FUTURE ENHANCEMENT - All search boxes are currently case sensitive.
 * <br>The search input and part/product names can all be converted to lower case before calling indexOf() method to simplify the searches.
 * @author James Armstrong
 */
public class JAC482JavaFXMLApplication extends Application {
    
    /**
     *
     * @param stage
     * @throws Exception
     */
    @Override
    public void start(Stage stage) throws Exception {
        Parent root = FXMLLoader.load(getClass().getResource("/view/MainMenu.fxml"));
        
        Scene scene = new Scene(root);
        
        stage.setScene(scene);
        stage.show();
    }
    
    /*
    * James Armstrong C482 Performance Assessment is the main folder containing the entire submission.
    * All files/code for the project itself is contained in the src folder.
    * javadocs generated by Apache NetBeans IDE 11.1 are all found in the only other folder, javadoc.
    */
    
    /**
     * Main method.
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        launch(args);
    }
    
}
